export const ErrorCodes = {
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MIGRATION_REQUIRED: 'MIGRATION_REQUIRED',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CONFIG_VERSION: 'INVALID_CONFIG_VERSION',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
